// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZavrsniRad.Models;

#nullable disable

namespace ZavrsniRad.Migrations
{
    [DbContext(typeof(PetTrackerDbContext))]
    [Migration("20260922122320_Subjekti_NazivTvrtkeNullable")]
    partial class Subjekti_NazivTvrtkeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiMikrocipaLjubimaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdentifikacijskaOznakaZivotinjeId")
                        .HasColumnType("int");

                    b.Property<string>("MjestoImplantacije")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentifikacijskaOznakaZivotinjeId");

                    b.ToTable("DetaljiMikrocipaLjubimaca");
                });

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiPrstenaLjubimaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<int>("IdentifikacijskaOznakaZivotinjeId")
                        .HasColumnType("int");

                    b.Property<string>("Materijal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Noga")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipPrstenaId")
                        .HasColumnType("int");

                    b.Property<string>("UnutarnjiPromjer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentifikacijskaOznakaZivotinjeId");

                    b.HasIndex("TipPrstenaId");

                    b.ToTable("DetaljiPrstenaLjubimaca");
                });

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiTetovazeLjubimaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdentifikacijskaOznakaZivotinjeId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PolozajTetovaze")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentifikacijskaOznakaZivotinjeId");

                    b.ToTable("DetaljiTetovazeLjubimaca");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Djelatnosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Djelatnosti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Drzave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerickaOznaka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OznakaAlpha2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OznakaAlpha3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Drzave");
                });

            modelBuilder.Entity("ZavrsniRad.Models.IdentifikacijskeOznakeVrste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("IdentifikacijskeOznakeVrste");
                });

            modelBuilder.Entity("ZavrsniRad.Models.IdentifikacijskeOznakeZivotinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Oznacavatelj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VrstaIdentifikacijskeOznakeId")
                        .HasColumnType("int");

                    b.Property<int>("ZivotinjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("VrstaIdentifikacijskeOznakeId");

                    b.HasIndex("ZivotinjaId");

                    b.ToTable("IdentifikacijskeOznakeZivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KorisniciAplikacije");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Naselja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("ZupanijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("ZupanijaId");

                    b.ToTable("Naselja");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Pasmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Pasmine");
                });

            modelBuilder.Entity("ZavrsniRad.Models.PravniOblici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PravniOblici");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Prehrana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrojObrokaDnevno")
                        .HasColumnType("int");

                    b.Property<string>("KolicinaHrane")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NamirniceZaIzbjegavanje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazivHrane")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Proizvodac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("VrstaHrane")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ZivotinjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZivotinjaId");

                    b.ToTable("Prehrana");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Spol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Spol");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Subjekti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazivTvrtke")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VrstaOsobeId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaSubjektaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VrstaOsobeId");

                    b.HasIndex("VrstaSubjektaId");

                    b.ToTable("Subjekti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiAdresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KucniBroj")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NaseljeId")
                        .HasColumnType("int");

                    b.Property<int>("SubjektId")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VrstaAdreseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NaseljeId");

                    b.HasIndex("SubjektId");

                    b.HasIndex("VrstaAdreseId");

                    b.ToTable("SubjektiAdrese");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiDetalji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumOsnivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DjelatnostId")
                        .HasColumnType("int");

                    b.Property<string>("MB")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MBO")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MBS")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("PravniOblikId")
                        .HasColumnType("int");

                    b.Property<int>("SubjektId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DjelatnostId");

                    b.HasIndex("PravniOblikId");

                    b.HasIndex("SubjektId");

                    b.ToTable("SubjektiDetalji");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiOsobe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SubjektiOsobe");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiRasporedi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktivanRaspored")
                        .HasColumnType("bit");

                    b.Property<int>("KorisniciAplikacijeId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubjektId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisniciAplikacijeId");

                    b.HasIndex("SubjektId");

                    b.ToTable("SubjektiRasporedi");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiRasporediRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RasporedSubjektaId")
                        .HasColumnType("int");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RasporedSubjektaId");

                    b.HasIndex("RolaId");

                    b.ToTable("SubjektiRasporediRole");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiVrste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SubjektiVrste");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiZivotinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjektId")
                        .HasColumnType("int");

                    b.Property<int>("ZivotinjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjektId");

                    b.HasIndex("ZivotinjaId");

                    b.ToTable("SubjektiZivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.TipPrstena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipPrstena");
                });

            modelBuilder.Entity("ZavrsniRad.Models.VrsteAdresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VrsteAdresa");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZdravstveniZapisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("VrstaZdravstvenogZapisaId")
                        .HasColumnType("int");

                    b.Property<int>("ZivotinjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VrstaZdravstvenogZapisaId");

                    b.HasIndex("ZivotinjaId");

                    b.ToTable("ZdravstveniZapisi");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZdravstveniZapisiVrste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZdravstveniZapisiVrste");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Zivotinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DatumRodenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpolId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaZivotinjePasminaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpolId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VrstaZivotinjePasminaId");

                    b.ToTable("Zivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZivotinjeStatusi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZivotinjeStatusi");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZivotinjeVrste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ZivotinjeVrste");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZivotinjeVrstePasmina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PasminaId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaZivotinjeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasminaId");

                    b.HasIndex("VrstaZivotinjeId");

                    b.ToTable("ZivotinjeVrstePasmina");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Zupanije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Zupanije");
                });

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiMikrocipaLjubimaca", b =>
                {
                    b.HasOne("ZavrsniRad.Models.IdentifikacijskeOznakeZivotinje", "IdentifikacijskeOznakeZivotinje")
                        .WithMany()
                        .HasForeignKey("IdentifikacijskaOznakaZivotinjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentifikacijskeOznakeZivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiPrstenaLjubimaca", b =>
                {
                    b.HasOne("ZavrsniRad.Models.IdentifikacijskeOznakeZivotinje", "IdentifikacijskeOznakeZivotinje")
                        .WithMany()
                        .HasForeignKey("IdentifikacijskaOznakaZivotinjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.TipPrstena", "TipPrstena")
                        .WithMany()
                        .HasForeignKey("TipPrstenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentifikacijskeOznakeZivotinje");

                    b.Navigation("TipPrstena");
                });

            modelBuilder.Entity("ZavrsniRad.Models.DetaljiTetovazeLjubimaca", b =>
                {
                    b.HasOne("ZavrsniRad.Models.IdentifikacijskeOznakeZivotinje", "IdentifikacijskeOznakeZivotinje")
                        .WithMany()
                        .HasForeignKey("IdentifikacijskaOznakaZivotinjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentifikacijskeOznakeZivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.IdentifikacijskeOznakeZivotinje", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Drzave", "Drzave")
                        .WithMany()
                        .HasForeignKey("DrzavaId");

                    b.HasOne("ZavrsniRad.Models.IdentifikacijskeOznakeVrste", "IdentifikacijskeOznakeVrste")
                        .WithMany()
                        .HasForeignKey("VrstaIdentifikacijskeOznakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Zivotinje", "Zivotinje")
                        .WithMany()
                        .HasForeignKey("ZivotinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzave");

                    b.Navigation("IdentifikacijskeOznakeVrste");

                    b.Navigation("Zivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Naselja", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Drzave", "Drzave")
                        .WithMany()
                        .HasForeignKey("DrzavaId");

                    b.HasOne("ZavrsniRad.Models.Zupanije", "Zupanije")
                        .WithMany()
                        .HasForeignKey("ZupanijaId");

                    b.Navigation("Drzave");

                    b.Navigation("Zupanije");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Prehrana", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Zivotinje", "Zivotinje")
                        .WithMany()
                        .HasForeignKey("ZivotinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Subjekti", b =>
                {
                    b.HasOne("ZavrsniRad.Models.SubjektiOsobe", "SubjektiOsobe")
                        .WithMany()
                        .HasForeignKey("VrstaOsobeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.SubjektiVrste", "SubjektiVrste")
                        .WithMany()
                        .HasForeignKey("VrstaSubjektaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjektiOsobe");

                    b.Navigation("SubjektiVrste");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiAdresa", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Naselja", "Naselja")
                        .WithMany()
                        .HasForeignKey("NaseljeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Subjekti", "Subjekti")
                        .WithMany()
                        .HasForeignKey("SubjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.VrsteAdresa", "VrstaAdresa")
                        .WithMany()
                        .HasForeignKey("VrstaAdreseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naselja");

                    b.Navigation("Subjekti");

                    b.Navigation("VrstaAdresa");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiDetalji", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Djelatnosti", "Djelatnosti")
                        .WithMany()
                        .HasForeignKey("DjelatnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.PravniOblici", "PravniOblici")
                        .WithMany()
                        .HasForeignKey("PravniOblikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Subjekti", "Subjekti")
                        .WithMany()
                        .HasForeignKey("SubjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Djelatnosti");

                    b.Navigation("PravniOblici");

                    b.Navigation("Subjekti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiRasporedi", b =>
                {
                    b.HasOne("ZavrsniRad.Models.KorisniciAplikacije", "KorisniciAplikacije")
                        .WithMany()
                        .HasForeignKey("KorisniciAplikacijeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Subjekti", "Subjekti")
                        .WithMany()
                        .HasForeignKey("SubjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KorisniciAplikacije");

                    b.Navigation("Subjekti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiRasporediRole", b =>
                {
                    b.HasOne("ZavrsniRad.Models.SubjektiRasporedi", "SubjektiRasporedi")
                        .WithMany()
                        .HasForeignKey("RasporedSubjektaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SubjektiRasporedi");
                });

            modelBuilder.Entity("ZavrsniRad.Models.SubjektiZivotinje", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Subjekti", "Subjekti")
                        .WithMany()
                        .HasForeignKey("SubjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Zivotinje", "Zivotinje")
                        .WithMany()
                        .HasForeignKey("ZivotinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subjekti");

                    b.Navigation("Zivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZdravstveniZapisi", b =>
                {
                    b.HasOne("ZavrsniRad.Models.ZdravstveniZapisiVrste", "ZdravstveniZapisiVrste")
                        .WithMany()
                        .HasForeignKey("VrstaZdravstvenogZapisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Zivotinje", "Zivotinje")
                        .WithMany()
                        .HasForeignKey("ZivotinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZdravstveniZapisiVrste");

                    b.Navigation("Zivotinje");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Zivotinje", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Spol", "Spol")
                        .WithMany()
                        .HasForeignKey("SpolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.ZivotinjeStatusi", "ZivotinjeStatusi")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.ZivotinjeVrstePasmina", "ZivotinjeVrstePasmina")
                        .WithMany()
                        .HasForeignKey("VrstaZivotinjePasminaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spol");

                    b.Navigation("ZivotinjeStatusi");

                    b.Navigation("ZivotinjeVrstePasmina");
                });

            modelBuilder.Entity("ZavrsniRad.Models.ZivotinjeVrstePasmina", b =>
                {
                    b.HasOne("ZavrsniRad.Models.Pasmine", "Pasmina")
                        .WithMany()
                        .HasForeignKey("PasminaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.ZivotinjeVrste", "ZivotinjeVrste")
                        .WithMany()
                        .HasForeignKey("VrstaZivotinjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasmina");

                    b.Navigation("ZivotinjeVrste");
                });
#pragma warning restore 612, 618
        }
    }
}
