// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZavrsniRad.Models;

#nullable disable

namespace ZavrsniRad.Migrations
{
    [DbContext(typeof(PetTrackerDbContext))]
    [Migration("20260831164615_PetTracker_KorisniciAplikacije")]
    partial class PetTracker_KorisniciAplikacije
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KorisniciAplikacije");
                });

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacijeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikAplikacijeId")
                        .HasColumnType("int");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikAplikacijeId");

                    b.HasIndex("RolaId");

                    b.ToTable("KorisniciAplikacijeRole");
                });

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacijeSubjekti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikAplikacijeId")
                        .HasColumnType("int");

                    b.Property<int>("SubjektId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikAplikacijeId");

                    b.HasIndex("SubjektId");

                    b.ToTable("KorisniciAplikacijeSubjekti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ZavrsniRad.Models.Subjekti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobitel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazivTvrtke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjekti");
                });

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacijeRole", b =>
                {
                    b.HasOne("ZavrsniRad.Models.KorisniciAplikacije", "KorisniciAplikacije")
                        .WithMany()
                        .HasForeignKey("KorisnikAplikacijeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KorisniciAplikacije");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZavrsniRad.Models.KorisniciAplikacijeSubjekti", b =>
                {
                    b.HasOne("ZavrsniRad.Models.KorisniciAplikacije", "KorisniciAplikacije")
                        .WithMany()
                        .HasForeignKey("KorisnikAplikacijeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZavrsniRad.Models.Subjekti", "Subjekti")
                        .WithMany()
                        .HasForeignKey("SubjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KorisniciAplikacije");

                    b.Navigation("Subjekti");
                });
#pragma warning restore 612, 618
        }
    }
}
