IF NOT EXISTS (SELECT TOP 1 * FROM Drzave WHERE id = 1)
BEGIN
INSERT INTO Drzave (Naziv, OznakaAlpha2, OznakaAlpha3, NumerickaOznaka, Status) VALUES
    ('AFGANISTAN', 'AF', 'AFG', '004', 1),
    ('ALBANIJA', 'AL', 'ALB', '008', 1),
    ('ALŽIR', 'DZ', 'DZA', '012', 1),
    ('AMERIČKA SAMOA', 'AS', 'ASM', '016', 1),
    ('AMERIČKI DJEVIČANSKI OTOCI', 'VI', 'VIR', '850', 1),
    ('ANDORA', 'AD', 'AND', '020', 1),
    ('ANGOLA', 'AO', 'AGO', '024', 1),
    ('ANGUILLA', 'AI', 'AIA', '660', 1),
    ('ANTARKTIKA', 'AQ', 'ATA', '010', 1),
    ('ANTIGVA I BARBUDA', 'AG', 'ATG', '028', 1),
    ('ARGENTINA', 'AR', 'ARG', '032', 1),
    ('ARMENIJA', 'AM', 'ARM', '051', 1),
    ('ARUBA', 'AW', 'ABW', '533', 1),
    ('AUSTRALIJA', 'AU', 'AUS', '036', 1),
    ('AUSTRIJA', 'AT', 'AUT', '040', 1),
    ('AZERBAJDŽAN', 'AZ', 'AZE', '031', 1),
    ('BAHAMI', 'BS', 'BHS', '044', 1),
    ('BAHREIN', 'BH', 'BHR', '048', 1),
    ('BANGLADEŠ', 'BD', 'BGD', '050', 1),
    ('BARBADOS', 'BB', 'BRB', '052', 1),
    ('BELGIJA', 'BE', 'BEL', '056', 1),
    ('BELIZE', 'BZ', 'BLZ', '084', 1),
    ('BENIN', 'BJ', 'BEN', '204', 1),
    ('BERMUDI', 'BM', 'BMU', '060', 1),
    ('BJELOKOSNA OBALA', 'CI', 'CIV', '384', 1),
    ('BJELORUSIJA', 'BY', 'BLR', '112', 1),
    ('BOCVANA', 'BW', 'BWA', '072', 1),
    ('BOLIVIJA, PLURINACIONALNA DRŽAVA', 'BO', 'BOL', '068', 1),
    ('BOSNA I HERCEGOVINA', 'BA', 'BIH', '070', 1),
    ('BOŽIĆNI OTOK', 'CX', 'CXR', '162', 1),
    ('BRAZIL', 'BR', 'BRA', '076', 1),
    ('BRITANSKI DJEVIČANSKI OTOCI', 'VG', 'VGB', '092', 1),
    ('BRITANSKI INDIJSKOOCEANSKI TERITORIJ', 'IO', 'IOT', '086', 1),
    ('BRUNEJ', 'BN', 'BRN', '096', 1),
    ('BUGARSKA', 'BG', 'BGR', '100', 1),
    ('BURKINA FASO', 'BF', 'BFA', '854', 1),
    ('BURUNDI', 'BI', 'BDI', '108', 1),
    ('BUTAN', 'BT', 'BTN', '064', 1),
    ('CIPAR', 'CY', 'CYP', '196', 1),
    ('CRNA GORA', 'ME', 'MNE', '499', 1),
    ('ČAD', 'TD', 'TCD', '148', 1),
    ('ČEŠKA', 'CZ', 'CZE', '203', 1),
    ('ČILE', 'CL', 'CHL', '152', 1),
    ('DANSKA', 'DK', 'DNK', '208', 1),
    ('DOMINIKA', 'DM', 'DMA', '212', 1),
    ('DOMINIKANSKA REPUBLIKA', 'DO', 'DOM', '214', 1),
    ('DŽIBUTI', 'DJ', 'DJI', '262', 1),
    ('EGIPAT', 'EG', 'EGY', '818', 1),
    ('EKVADOR', 'EC', 'ECU', '218', 1),
    ('EKVATORSKA GVINEJA', 'GQ', 'GNQ', '226', 1),
    ('ERITREJA', 'ER', 'ERI', '232', 1),
    ('ESTONIJA', 'EE', 'EST', '233', 1),
    ('ETIOPIJA', 'ET', 'ETH', '231', 1),
    ('FALKLANDI (MALVINI)', 'FK', 'FLK', '238', 1),
    ('FEROJSKI (OVČJI) OTOCI', 'FO', 'FRO', '234', 1),
    ('FIDŽI', 'FJ', 'FJI', '242', 1),
    ('FILIPINI', 'PH', 'PHL', '608', 1),
    ('FINSKA', 'FI', 'FIN', '246', 1),
    ('FRANCUSKA', 'FR', 'FRA', '250', 1),
    ('FRANCUSKA GVAJANA', 'GF', 'GUF', '254', 1),
    ('FRANCUSKA POLINEZIJA', 'PF', 'PYF', '258', 1),
    ('FRANCUSKI JUŽNI TERITORIJI', 'TF', 'ATF', '260', 1),
    ('GABON', 'GA', 'GAB', '266', 1),
    ('GAMBIJA', 'GM', 'GMB', '270', 1),
    ('GANA', 'GH', 'GHA', '288', 1),
    ('GIBRALTAR', 'GI', 'GIB', '292', 1),
    ('GRČKA', 'GR', 'GRC', '300', 1),
    ('GRENADA', 'GD', 'GRD', '308', 1),
    ('GRENLAND', 'GL', 'GRL', '304', 1),
    ('GRUZIJA', 'GE', 'GEO', '268', 1),
    ('GUADELOUPE', 'GP', 'GLP', '312', 1),
    ('GUAM', 'GU', 'GUM', '316', 1),
    ('GUERNSEY', 'GG', 'GGY', '831', 1),
    ('GVAJANA', 'GY', 'GUY', '328', 1),
    ('GVATEMALA', 'GT', 'GTM', '320', 1),
    ('GVINEJA', 'GN', 'GIN', '324', 1),
    ('GVINEJA BISAU', 'GW', 'GNB', '624', 1),
    ('HAITI', 'HT', 'HTI', '332', 1),
    ('HONDURAS', 'HN', 'HND', '340', 1),
    ('HONG KONG', 'HK', 'HKG', '344', 1),
    ('HRVATSKA', 'HR', 'HRV', '191', 1),
    ('INDIJA', 'IN', 'IND', '356', 1),
    ('INDONEZIJA', 'ID', 'IDN', '360', 1),
    ('IRAK', 'IQ', 'IRQ', '368', 1),
    ('IRAN, ISLAMSKA REPUBLIKA', 'IR', 'IRN', '364', 1),
    ('IRSKA', 'IE', 'IRL', '372', 1),
    ('ISLAND', 'IS', 'ISL', '352', 1),
    ('ITALIJA', 'IT', 'ITA', '380', 1),
    ('IZRAEL', 'IL', 'ISR', '376', 1),
    ('JAMAJKA', 'JM', 'JAM', '388', 1),
    ('JAPAN', 'JP', 'JPN', '392', 1),
    ('JEMEN', 'YE', 'YEM', '887', 1),
    ('JERSEY', 'JE', 'JEY', '832', 1),
    ('JORDAN', 'JO', 'JOR', '400', 1),
    ('JUŽNA DŽORDŽIJA I OTOCI JUŽNI SENDVIČ', 'GS', 'SGS', '239', 1),
    ('JUŽNOAFRIČKA REPUBLIKA', 'ZA', 'ZAF', '710', 1),
    ('KAJMANSKI OTOCI', 'KY', 'CYM', '136', 1),
    ('KAMBODŽA', 'KH', 'KHM', '116', 1),
    ('KAMERUN', 'CM', 'CMR', '120', 1),
    ('KANADA', 'CA', 'CAN', '124', 1),
    ('KATAR', 'QA', 'QAT', '634', 1),
    ('KAZAHSTAN', 'KZ', 'KAZ', '398', 1),
    ('KENIJA', 'KE', 'KEN', '404', 1),
    ('KINA', 'CN', 'CHN', '156', 1),
    ('KIRGISTAN', 'KG', 'KGZ', '417', 1),
    ('KIRIBATI', 'KI', 'KIR', '296', 1),
    ('KOKOSOVI OTOCI (KEELING)', 'CC', 'CCK', '166', 1),
    ('KOLUMBIJA', 'CO', 'COL', '170', 1),
    ('KOMORI', 'KM', 'COM', '174', 1),
    ('KONGO', 'CG', 'COG', '178', 1),
    ('KONGO, DEMOKRATSKA REPUBLIKA', 'CD', 'COD', '180', 1),
    ('KOREJA, DEMOKRATSKA NARODNA REPUBLIKA', 'KP', 'PRK', '408', 1),
    ('KOREJA, REPUBLIKA', 'KR', 'KOR', '410', 1),
    ('KOSTARIKA', 'CR', 'CRI', '188', 1),
    ('KUBA', 'CU', 'CUB', '192', 1),
    ('KUKOVI OTOCI', 'CK', 'COK', '184', 1),
    ('KUVAJT', 'KW', 'KWT', '414', 1),
    ('LAOS, NARODNA DEMOKRATSKA REPUBLIKA', 'LA', 'LAO', '418', 1),
    ('LESOTO', 'LS', 'LSO', '426', 1),
    ('LETONIJA', 'LV', 'LVA', '428', 1),
    ('LIBANON', 'LB', 'LBN', '422', 1),
    ('LIBERIJA', 'LR', 'LBR', '430', 1),
    ('LIBIJA', 'LY', 'LBY', '434', 1),
    ('LIHTENŠTAJN', 'LI', 'LIE', '438', 1),
    ('LITVA', 'LT', 'LTU', '440', 1),
    ('LUKSEMBURG', 'LU', 'LUX', '442', 1),
    ('MADAGASKAR', 'MG', 'MDG', '450', 1),
    ('MADŽARSKA', 'HU', 'HUN', '348', 1),
    ('MAKAO', 'MO', 'MAC', '446', 1),
    ('MAKEDONIJA', 'MK', 'MKD', '807', 1),
    ('MALAVI', 'MW', 'MWI', '454', 1),
    ('MALDIVI', 'MV', 'MDV', '462', 1),
    ('MALEZIJA', 'MY', 'MYS', '458', 1),
    ('MALI', 'ML', 'MLI', '466', 1),
    ('MALTA', 'MT', 'MLT', '470', 1),
    ('MAROKO', 'MA', 'MAR', '504', 1),
    ('MARŠALOVI OTOCI', 'MH', 'MHL', '584', 1),
    ('MARTINIQUE', 'MQ', 'MTQ', '474', 1),
    ('MAURICIJUS', 'MU', 'MUS', '480', 1),
    ('MAURITANIJA', 'MR', 'MRT', '478', 1),
    ('MAYOTTE', 'YT', 'MYT', '175', 1),
    ('MEKSIKO', 'MX', 'MEX', '484', 1),
    ('MIJANMAR', 'MM', 'MMR', '104', 1),
    ('MIKRONEZIJA, SAVEZNE DRŽAVE', 'FM', 'FSM', '583', 1),
    ('MOLDAVIJA', 'MD', 'MDA', '498', 1),
    ('MONAKO', 'MC', 'MCO', '492', 1),
    ('MONGOLIJA', 'MN', 'MNG', '496', 1),
    ('MONTSERRAT', 'MS', 'MSR', '500', 1),
    ('MOZAMBIK', 'MZ', 'MOZ', '508', 1),
    ('NAMIBIJA', 'NA', 'NAM', '516', 1),
    ('NAURU', 'NR', 'NRU', '520', 1),
    ('NEPAL', 'NP', 'NPL', '524', 1),
    ('NIGER', 'NE', 'NER', '562', 1),
    ('NIGERIJA', 'NG', 'NGA', '566', 1),
    ('NIKARAGVA', 'NI', 'NIC', '558', 1),
    ('NIUE', 'NU', 'NIU', '570', 1),
    ('NIZOZEMSKA', 'NL', 'NLD', '528', 1),
    ('NIZOZEMSKI ANTILI', 'AN', 'ANT', '530', 1),
    ('NORVEŠKA', 'NO', 'NOR', '578', 1),
    ('NOVA KALEDONIJA', 'NC', 'NCL', '540', 1),
    ('NOVI ZELAND', 'NZ', 'NZL', '554', 1),
    ('NJEMAČKA', 'DE', 'DEU', '276', 1),
    ('OMAN', 'OM', 'OMN', '512', 1),
    ('OTOCI ÅLAND', 'AX', 'ALA', '248', 1),
    ('OTOCI TURKS I CAICOS', 'TC', 'TCA', '796', 1),
    ('OTOK BOUVET', 'BV', 'BVT', '074', 1),
    ('OTOK HEARD I OTOCI MCDONALD', 'HM', 'HMD', '334', 1),
    ('OTOK MAN', 'IM', 'IMN', '833', 1),
    ('OTOK NORFOLK', 'NF', 'NFK', '574', 1),
    ('PAKISTAN', 'PK', 'PAK', '586', 1),
    ('PALAU', 'PW', 'PLW', '585', 1),
    ('PALESTINSKO PODRUČJE, OKUPIRANO', 'PS', 'PSE', '275', 1),
    ('PANAMA', 'PA', 'PAN', '591', 1),
    ('PAPUA NOVA GVINEJA', 'PG', 'PNG', '598', 1),
    ('PARAGVAJ', 'PY', 'PRY', '600', 1),
    ('PERU', 'PE', 'PER', '604', 1),
    ('PITCAIRN', 'PN', 'PCN', '612', 1),
    ('POLJSKA', 'PL', 'POL', '616', 1),
    ('PORTORIKO', 'PR', 'PRI', '630', 1),
    ('PORTUGAL', 'PT', 'PRT', '620', 1),
    ('RÉUNION', 'RE', 'REU', '638', 1),
    ('RUANDA', 'RW', 'RWA', '646', 1),
    ('RUMUNJSKA', 'RO', 'ROU', '642', 1),
    ('RUSIJA', 'RU', 'RUS', '643', 1),
    ('SAD', 'US', 'USA', '840', 1),
    ('SALVADOR', 'SV', 'SLV', '222', 1),
    ('SAMOA', 'WS', 'WSM', '882', 1),
    ('SAN MARINO', 'SM', 'SMR', '674', 1),
    ('SAUDIJSKA ARABIJA', 'SA', 'SAU', '682', 1),
    ('SEJŠELI', 'SC', 'SYC', '690', 1),
    ('SENEGAL', 'SN', 'SEN', '686', 1),
    ('SIJERA LEONE', 'SL', 'SLE', '694', 1),
    ('SINGAPUR', 'SG', 'SGP', '702', 1),
    ('SIRIJA', 'SY', 'SYR', '760', 1),
    ('SJEVERNI MARIJANSKI OTOCI', 'MP', 'MNP', '580', 1),
    ('SLOVAČKA', 'SK', 'SVK', '703', 1),
    ('SLOVENIJA', 'SI', 'SVN', '705', 1),
    ('SOLOMONSKI OTOCI', 'SB', 'SLB', '090', 1),
    ('SOMALIJA', 'SO', 'SOM', '706', 1),
    ('SRBIJA', 'RS', 'SRB', '688', 1),
    ('SREDNJOAFRIČKA REPUBLIKA', 'CF', 'CAF', '140', 1),
    ('SUDAN', 'SD', 'SDN', '736', 1),
    ('SURINAM', 'SR', 'SUR', '740', 1),
    ('SVALBARD I JAN MAYEN', 'SJ', 'SJM', '744', 1),
    ('SVAZI', 'SZ', 'SWZ', '748', 1),
    ('SVETA HELENA, ASCENSION I TRISTAN DA CUNHA', 'SH', 'SHN', '654', 1),
    ('SVETA LUCIJA', 'LC', 'LCA', '662', 1),
    ('SVETI BARTOLOMEJ', 'BL', 'BLM', '652', 1),
    ('SVETA STOLICA (DRŽAVA VATIKANSKOG GRADA)', 'VA', 'VAT', '336', 1),
    ('SVETI KRISTOFOR I NEVIS', 'KN', 'KNA', '659', 1),
    ('SVETI MARTIN', 'MF', 'MAF', '663', 1),
    ('SVETI PETAR I MIKELON', 'PM', 'SPM', '666', 1),
    ('SVETI TOMA I PRINSIPE', 'ST', 'STP', '678', 1),
    ('SVETI VINCENT I GRENADINI', 'VC', 'VCT', '670', 1),
    ('ŠPANJOLSKA', 'ES', 'ESP', '724', 1),
    ('ŠRI LANKA', 'LK', 'LKA', '144', 1),
    ('ŠVEDSKA', 'SE', 'SWE', '752', 1),
    ('ŠVICARSKA', 'CH', 'CHE', '756', 1),
    ('TADŽIKISTAN', 'TJ', 'TJK', '762', 1),
    ('TAJLAND', 'TH', 'THA', '764', 1),
    ('TAJVAN, KINESKA PROVINCIJA', 'TW', 'TWN', '158', 1),
    ('TANZANIJA, UJEDINJENA REPUBLIKA', 'TZ', 'TZA', '834', 1),
    ('TIMOR LESTE', 'TL', 'TLS', '626', 1),
    ('TOGO', 'TG', 'TGO', '768', 1),
    ('TOKELAU', 'TK', 'TKL', '772', 1),
    ('TONGA', 'TO', 'TON', '776', 1),
    ('TRINIDAD I TOBAGO', 'TT', 'TTO', '780', 1),
    ('TUNIS', 'TN', 'TUN', '788', 1),
    ('TURKMENISTAN', 'TM', 'TKM', '795', 1),
    ('TURSKA', 'TR', 'TUR', '792', 1),
    ('TUVALU', 'TV', 'TUV', '798', 1),
    ('UGANDA', 'UG', 'UGA', '800', 1),
    ('UJEDINJENE DRŽAVE MANJIH PACIFIČKIH OTOKA', 'UM', 'UMI', '581', 1),
    ('UJEDINJENI ARAPSKI EMIRATI', 'AE', 'ARE', '784', 1),
    ('UKRAJINA', 'UA', 'UKR', '804', 1),
    ('URUGVAJ', 'UY', 'URY', '858', 1),
    ('UZBEKISTAN', 'UZ', 'UZB', '860', 1),
    ('VANUATU', 'VU', 'VUT', '548', 1),
    ('VELIKA BRITANIJA', 'GB', 'GBR', '826', 1),
    ('VENEZUELA, BOLIVARIJANSKA REPUBLIKA', 'VE', 'VEN', '862', 1),
    ('VIJETNAM', 'VN', 'VNM', '704', 1),
    ('WALLIS I FUTUNA', 'WF', 'WLF', '876', 1),
    ('ZAMBIJA', 'ZM', 'ZMB', '894', 1),
    ('ZAPADNA SAHARA', 'EH', 'ESH', '732', 1),
    ('ZELENORTSKA REPUBLIKA', 'CV', 'CPV', '132', 1),
    ('ZIMBABVE', 'ZW', 'ZWE', '716', 1);
END
